name: Build PR
on:
  repository_dispatch:
    types: [osac-pr-preview-build]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          path: "deploy"

      - name: Checkout That pr
        uses: actions/checkout@v2
        with:
          repository: osac/osac.github.io
          ref: ${{ github.event.client_payload.ref }}
          submodules: true # Fetch Hugo themes (true OR recursive)
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "site"

      # install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      # build website
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/site
          hugo --minify
          rm ./public/CNAME ./public/.nojekyll
          mv ./public $GITHUB_WORKSPACE/deploy/${{github.event.client_payload.prId}}

      - name: Custom files
        run: |
          echo "beta.osac.org.np" > $GITHUB_WORKSPACE/deploy/CNAME
          echo "" > $GITHUB_WORKSPACE/deploy/.nojekyll
          echo "" > $GITHUB_WORKSPACE/deploy/index.html

      # push the generated content into the `gh-pages` branch.
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: $GITHUB_WORKSPACE/deploy
          force: false
